# Form implementation generated from reading ui file 'commitfilesearchbar.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.localization import *
from gitfourchette.qt import *


class Ui_CommitFileSearchBar(object):
    def setupUi(self, CommitFileSearchBar):
        CommitFileSearchBar.setObjectName("CommitFileSearchBar")
        CommitFileSearchBar.resize(520, 28)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CommitFileSearchBar.sizePolicy().hasHeightForWidth())
        CommitFileSearchBar.setSizePolicy(sizePolicy)
        CommitFileSearchBar.setAutoFillBackground(True)
        self.horizontalLayout = QHBoxLayout(CommitFileSearchBar)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QLineEdit(parent=CommitFileSearchBar)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.filterOnlyCheckBox = QCheckBox(parent=CommitFileSearchBar)
        self.filterOnlyCheckBox.setObjectName("filterOnlyCheckBox")
        self.horizontalLayout.addWidget(self.filterOnlyCheckBox)
        self.forwardButton = QToolButton(parent=CommitFileSearchBar)
        self.forwardButton.setText("↓")
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.backwardButton = QToolButton(parent=CommitFileSearchBar)
        self.backwardButton.setText("↑")
        self.backwardButton.setObjectName("backwardButton")
        self.horizontalLayout.addWidget(self.backwardButton)
        self.closeButton = QToolButton(parent=CommitFileSearchBar)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)

        self.retranslateUi(CommitFileSearchBar)
        QMetaObject.connectSlotsByName(CommitFileSearchBar)

    def retranslateUi(self, CommitFileSearchBar):
        CommitFileSearchBar.setWindowTitle(_p("CommitFileSearchBar", "Commit file search"))
        self.lineEdit.setPlaceholderText(_p("CommitFileSearchBar", "Path or file name…"))
        self.filterOnlyCheckBox.setText(_p("CommitFileSearchBar", "Only show matching commits"))
        self.backwardButton.setToolTip(_p("CommitFileSearchBar", "Previous matching commit"))
        self.forwardButton.setToolTip(_p("CommitFileSearchBar", "Next matching commit"))
        self.closeButton.setToolTip(_p("CommitFileSearchBar", "Close"))
        self.closeButton.setText(_p("CommitFileSearchBar", "Done"))
